// Generated by CoffeeScript 1.3.3

/*
  mdhtmlform - Simple Example
  This file just handles form submissions for this example.
*/


(function() {

  $(function() {
    return $("button.submit").on("click", function(e) {
      var count;
      e.preventDefault();
      count = 1;
      return $("textarea.mdhtmlform-html").each(function() {
        var html;
        html = $(this).val();
        alert("You can submit multiple textareas, here is # " + count + ": " + html);
        return count++;
      });
    });
  });

}).call(this);
