// Generated by CoffeeScript 1.3.3

/*
Markdown HTML Form

Copyright (c) 2013 Justin McCandless (justinmccandless.com)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var MdHtmlForm;

  MdHtmlForm = (function() {

    MdHtmlForm.prototype.form = null;

    MdHtmlForm.prototype.html = "";

    MdHtmlForm.prototype.md = "";

    MdHtmlForm.prototype.selHtml = ".mdhtmlform-html";

    MdHtmlForm.prototype.selMd = ".mdhtmlform-md";

    function MdHtmlForm(obj) {
      var me;
      this.md = $(this.selMd).val();
      me = this;
      $(this.selMd).on("keyup", function(e) {
        return me.updateMdToHtml();
      });
      $(this.selHtml).bind('hallomodified', function(event, data) {
        return me.updateHtmlToMd();
      });
      this.updateMdToHtml();
    }

    MdHtmlForm.prototype.updateMdToHtml = function() {
      this.md = $(this.selMd).val();
      this.convertMdToHtml();
      return this.renderHtml();
    };

    MdHtmlForm.prototype.updateHtmlToMd = function() {
      this.html = $(this.selHtml).html();
      this.convertHtmlToMd();
      return this.renderMd();
    };

    MdHtmlForm.prototype.convertMdToHtml = function() {
      var converter;
      if (window.hasOwnProperty("Showdown")) {
        converter = new Showdown.converter();
        return this.html = converter.makeHtml(this.md);
      } else {
        return console.log("Error: mdhtmlform: Showdown not properly included");
      }
    };

    MdHtmlForm.prototype.convertHtmlToMd = function() {
      if (window.hasOwnProperty("toMarkdown")) {
        return this.md = toMarkdown(this.html);
      } else {
        return console.log("Error: mdhtmlform: to-markdown not properly included");
      }
    };

    MdHtmlForm.prototype.renderHtml = function() {
      $("div" + this.selHtml).html(this.html);
      return this.renderTextarea();
    };

    MdHtmlForm.prototype.renderMd = function() {
      $(this.selMd).val(this.md);
      return this.renderTextarea();
    };

    MdHtmlForm.prototype.renderTextarea = function() {
      return $("textarea" + this.selHtml).html(this.html);
    };

    return MdHtmlForm;

  })();

  $(function() {
    return $("form.mdhtmlform").each(function() {
      return new MdHtmlForm(this);
    });
  });

}).call(this);
