// Generated by CoffeeScript 1.3.3

/*
  mdhtmlform - Two-way Example
  This file just handles form submissions for this example.
*/


(function() {

  $(function() {
    return $("button.submit").on("click", function(e) {
      var html;
      e.preventDefault();
      html = $("textarea.mdhtmlform-html").val();
      return alert("Submit the raw html textarea: " + html);
    });
  });

}).call(this);
